<?php $this->render('common/header'); ?>
<?php $this->render('common/session'); ?>
<head><title>Cadastro - Moveis</title>
<head>
    <!-- Adicionando Javascript -->
    <script type="text/javascript" >
    
    function limpa_formulário_cep() {
            //Limpa valores do formulário de cep.
            document.getElementById('rua').value=("");
            document.getElementById('bairro').value=("");
            document.getElementById('cidade').value=("");
            document.getElementById('uf').value=("");
            document.getElementById('ibge').value=("");
    }

    function meu_callback(conteudo) {
        if (!("erro" in conteudo)) {
            //Atualiza os campos com os valores.
            document.getElementById('rua').value=(conteudo.logradouro);
            document.getElementById('bairro').value=(conteudo.bairro);
            document.getElementById('cidade').value=(conteudo.localidade);
            document.getElementById('uf').value=(conteudo.uf);
            document.getElementById('ibge').value=(conteudo.ibge);
        } //end if.
        else {
            //CEP não Encontrado.
            limpa_formulário_cep();
            alert("CEP não encontrado.");
        }
    }
        
    function pesquisacep(valor) {

        //Nova variável "cep" somente com dígitos.
        var cep = valor.replace(/\D/g, '');

        //Verifica se campo cep possui valor informado.
        if (cep != "") {

            //Expressão regular para validar o CEP.
            var validacep = /^[0-9]{8}$/;

            //Valida o formato do CEP.
            if(validacep.test(cep)) {

                //Preenche os campos com "..." enquanto consulta webservice.
                document.getElementById('rua').value="...";
                document.getElementById('bairro').value="...";
                document.getElementById('cidade').value="...";
                document.getElementById('uf').value="...";
                document.getElementById('ibge').value="...";

                //Cria um elemento javascript.
                var script = document.createElement('script');

                //Sincroniza com o callback.
                script.src = '//viacep.com.br/ws/'+ cep + '/json/?callback=meu_callback';

                //Insere script no documento e carrega o conteúdo.
                document.body.appendChild(script);

            } //end if.
            else {
                //cep é inválido.
                limpa_formulário_cep();
                alert("Formato de CEP inválido.");
            }
        } //end if.
        else {
            //cep sem valor, limpa formulário.
            limpa_formulário_cep();
        }
    };

    </script>
    </head>

    <div class="page-header">
        <?php $this->render('common/login'); ?><!--logo-->
        <?php $this->render('common/logout'); ?><!--logout-->
    </div>
    <div class="container">
        <?php $this->render('common/navbar'); ?><!--navbar-->
<!--        <script type="text/javascript">
            $(document).ready(function()){
                $("input[name='cep']").blur(function()){
                    var $rua = $("input[name='rua']");
                    $.getJSON(,{
                        cep: $( this ).val()
                    },function( json )){
                        $rua.val( json.rua );
                    };
                };
            };
        </script>-->

        <form class="form-horizontal" action="<?= url()->route('cadastro.cadastroImoveis'); ?>" method="post" enctype="multipart/form-data">
            <div class="form-group">
                    <label for="codigo" class="col-sm-2 control-label">Código</label>
                    <div class="col-sm-2">
                            <input type="text" value="" name="codigo" class="form-control" id="codigo" placeholder="Código do Imovel">
                    </div>
            </div>
            <div class="form-group">
                    <label for="titulo" class="col-sm-2 control-label">Titulo</label>
                    <div class="col-sm-3">
                            <input type="text" value="" name="titulo" class="form-control" id="nome" placeholder="Titulo do Imóvel">
                    </div>
                    <label for="tipo" class="col-sm-1 control-label">Tipo</label>
                    <div class="col-sm-2">
                        <div class="col-sm-1">
                            <select class="selectpicker show-tick" name="tipo">
                                <option value="Casa">Casa</option>
                                <option value="Apartamento">Apartamento</option>
                                <option value="Sobrado">Sobrado</option>
                                <option value="Chacara">Chacara</option>
                                <option value="Kitnet">Kitnet</option>
                            </select>
                        </div>
                    </div>
            </div>
            
            <div class="form-group">
                    <label class="col-sm-2 control-label">Cep:</label>
                    <div class="col-sm-2">
                        <input class="form-control" placeholder="Cep" name="cep" type="text" id="cep" value="" size="10" maxlength="9"
                    onblur="pesquisacep(this.value);" />
                    </div>
                    <label for="ruaa" class="col-sm-1 control-label">Rua</label>
                    <div class="col-sm-4">
                            <input name="rua" type="text" id="rua" size="60" class="form-control" placeholder="Rua">
                    </div>
                    <label for="numero" class="col-sm-1 control-label">Numero</label>
                    <div class="col-sm-2">
                            <input type="text" value="" name="numero" class="form-control" id="numero" placeholder="Numero">
                    </div>
            </div>
            <div class="form-group">
                    <label for="cidade" class="col-sm-2 control-label">Cidade</label>
                    <div class="col-sm-2">
                            <input name="cidade" type="text" id="cidade" size="40" class="form-control" placeholder="Cidade">
                    </div>
                    <label for="uf" class="col-sm-1 control-label">Estado</label>
                    <div class="col-sm-1">
                            <input name="uf" type="text" id="uf" size="60" class="form-control" placeholder="Estado">
                    </div><!--                    
                    <label for="estado" class="col-sm-1 control-label" name="uf" type="text" id="uf" size="2">Estado</label>
                    <div class="col-sm-1">
                        <select class="selectpicker" data-live-search="true" name="uf" type="text" id="uf" size="2">
                                <option  data-tokens="AL" value="AL">AL</option>
                                <option  data-tokens="AM" value="AM">AM</option>
                                <option  data-tokens="AP" value="AP">AP</option>
                                <option  data-tokens="BA" value="BA">BA</option>
                                <option  data-tokens="CE" value="CE">CE</option>
                                <option  data-tokens="DF" value="DF">DF</option>
                                <option  data-tokens="ES" value="ES">ES</option>
                                <option  data-tokens="GO" value="GO">GO</option>
                                <option  data-tokens="MA" value="MA">MA</option>
                                <option  data-tokens="MG" value="MG">MG</option>
                                <option  data-tokens="MS" value="MS">MS</option>
                                <option  data-tokens="MT" value="MT">MT</option>
                                <option  data-tokens="PA" value="PA">PA</option>
                                <option  data-tokens="PB" value="PB">PB</option>
                                <option  data-tokens="PE" value="PE">PE</option>
                                <option  data-tokens="PI" value="PI">PI</option>
                                <option  data-tokens="PR" value="PR">PR</option>
                                <option  data-tokens="RJ" value="RJ">RJ</option>
                                <option  data-tokens="RN" value="RN">RN</option>
                                <option  data-tokens="RO" value="RO">RO</option>
                                <option  data-tokens="RR" value="RR">RR</option>
                                <option  data-tokens="RS" value="RS">RS</option>
                                <option  data-tokens="SC" value="SC">SC</option>
                                <option  data-tokens="SE" value="SE">SE</option>
                                <option  data-tokens="SP" value="SP">SP</option>
                                <option  data-tokens="TO" value="TO">TO</option>
                            </select>
                    </div>-->
                    
            </div>
            <div class="form-group">
                <label for="bairro" class="col-sm-2 control-label">Bairro</label>
                    <div class="col-sm-4">
                            <input name="bairro" type="text" id="bairro" size="40" class="form-control" placeholder="Bairro">
                    </div>
                    <label for="complemente" class="col-sm-1 control-label">Complemento</label>
                    <div class="col-sm-4">
                            <input type="text" value="" name="complemento" class="form-control" id="quantidade" placeholder="Complemento">
                    </div>
            </div>    
            <div class="form-group">
                    <label for="preco" class="col-sm-2 control-label">Preço</label>
                    <div class="col-sm-2">
                            <input type="text" value="" name="preco" class="form-control" id="foto" placeholder="Preço">
                    </div>
                    <div class="col-sm-2">
                        <select class="selectpicker show-tick" name="forma">
                            <option value="venda">Venda</option>
                            <option value="Aluguel">Aluguel</option>
                            <option value="Temporada">Temporada</option>
                          </select>
                    </div>
            </div>
             <div class="form-group">
                    <label for="area" class="col-sm-2 control-label">Area</label>
                    <div class="col-sm-2">
                        <input type="text" value="" name="area" class="form-control" id="foto" placeholder="Área Mt²">
                    </div>
            </div>
            <div class="form-group">
                    <label for="quarto" class="col-sm-2 control-label">Quarto</label>
                    <div class="col-sm-1">
                        <select name="quarto">
                            <option value="0">0</option>
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                            <option value="5">5</option>
                            <option value="6">6</option>
                            <option value="7">7</option>
                            <option value="8">8</option>
                            <option value="9">9</option>
                            <option value="10">10</option>
                         </select>
                    </div>
                    <label for="suite" class="col-sm-1 control-label">Suite</label>
                    <div class="col-sm-1">
                        <select name="suite">
                            <option value="0">0</option>
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                            <option value="5">5</option>
                            <option value="6">6</option>
                            <option value="7">7</option>
                            <option value="8">8</option>
                            <option value="9">9</option>
                            <option value="10">10</option>
                          </select>
                    </div>
                    <label for="banheiro" class="col-sm-1 control-label">Banheiro</label>
                    <div class="col-sm-1">
                        <select name="banheiro">
                            <option value="0">0</option>
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                            <option value="5">5</option>
                            <option value="6">6</option>
                            <option value="7">7</option>
                            <option value="8">8</option>
                            <option value="9">9</option>
                            <option value="10">10</option>
                          </select>
                    </div>
                    <label for="sala" class="col-sm-1 control-label">Sala</label>
                    <div class="col-sm-1">
                        <select name="sala">
                            <option value="0">0</option>
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                            <option value="5">5</option>
                            <option value="6">6</option>
                            <option value="7">7</option>
                            <option value="8">8</option>
                            <option value="9">9</option>
                            <option value="10">10</option>
                          </select>
                    </div>
                    <label for="garagem" class="col-sm-1 control-label">Garagem</label>
                    <div class="col-sm-1">
                        <select name="garagem">
                            <option value="0">0</option>
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                            <option value="5">5</option>
                            <option value="6">6</option>
                            <option value="7">7</option>
                            <option value="8">8</option>
                            <option value="9">9</option>
                            <option value="10">10</option>
                          </select>
                    </div>
            </div>
            <div class="form-group">
                    <label for="imagem" class="col-sm-2 control-label">Imagem</label>
                    <div class="col-sm-4">
                        <input type="file" value="" name="arquivo" class="form-control" id="imagem">
                    </div>
            </div>
            
            <label class="col-sm-2 control-label">IBGE:</label>
            <div class="col-sm-1">
            <input class="form-control" name="ibge" type="text" id="ibge" size="8" /><br /><br />
            </div>
            <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-success">Cadastrar</button>
                    </div>
            </div>
               
                <?php if (session()->has('_sucesso')): ?>
                    <div class="alert alert-success" role="alert"><?= session()->getAndRemove('_sucesso'); ?></div>
                <?php endif; ?>
                <?php if (session()->has('_erro')): ?>
                    <div class="alert alert-danger" role="alert"><?= session()->getAndRemove('_erro'); ?></div>
                <?php endif; ?>
            
        </form>
        
    </div>

<?php $this->render('common/footer'); ?>
