<?php
$this->render('common/header');
if ((!isset($_SESSION['email_login']) == true) and ( !isset($_SESSION['pass_login']) == true)) {
    unset($_SESSION['email_login']);
    unset($_SESSION['pass_login']);
    session()->put('_erro', 'Erro Login');
    return redirect()->route('index');
}

$logado = $_SESSION['email_login'];
?>
<div id="main" class="container-fluid">

    <div id="top" class="row">
        <div class="col-md-3">
            <h2 class="page-header">Funcionários</h2>
        </div>
        <div class="col-md-6">
            <div class="input-group h2">
                <input name="data[search]" class="form-control" id="search" type="text" placeholder="Pesquisa de Itens">
                <span class="input-group-btn">
                    <button type="submit" class="btn btn-primary">
                        <span class="glyphicon glyphicon-search"></span>
                    </button>
                </span>
            </div>
        </div>
        
        <div class="col-md-3">
            <a href="<?= url()->route('cadastro.index'); ?>" class="btn btn-primary pull-right h2">Novo Funcionário</a>
        </div>
        <div class="col-md-6 text-center">
            <a href="<?= url()->route('menu.index'); ?>" class="btn btn-primary pull-right h2">Home</a>
            
        </div>
    </div> <!-- /#top -->
    <!--mensagem de erro DELETAR!!!-->
    <?php $this->render('common/logout'); ?><!--logout-->
    <?php if(session()->has('_erro')): ?>
        <div class="alert alert-danger" role="alert"><?=session()->getAndRemove('_erro');?></div>
    <?php endif;  ?>
        
    <?php if (session()->has('_sucesso')): ?>
        <div class="alert alert-success" role="alert">
            <?= session()->getAndRemove('_sucesso'); ?>
        </div>
    <?php endif; ?>
        
    <hr />
    
    <div id="list" class="row">
        <div class="table table-responsive col-md-12">            
            <table class="table table-striped" cellspacing="0" cellpadding="0">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Nome</th>
                        <th>Telefone</th>
                        <th>Email</th>
                        <th class="actions">Ações</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($pessoas as $funcionarios): ?>
                        <tr>
                            <td><?= $funcionarios->id; ?></td>
                            <td><?= $funcionarios->nome; ?></td>
                            <td><?= $funcionarios->fone; ?></td>
                            <td><?= $funcionarios->email; ?></td>
                            <td class="actions">
                                <a href="<?=url()->route('eventos.index', ['pessoa' =>$funcionarios->id]);?>" class="btn btn-success btn-xs">Agenda</a> 
                                <a href="<?=url()->route('pessoa.cadastrar', ['pessoa' =>$funcionarios->id]);?>" class="btn btn-warning btn-xs">Editar</a>
                                <a href="<?= url()->route('pessoa.deletar', ['pessoa' => $funcionarios->id]); ?>" class="btn btn-danger btn-xs">Excluir</a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>

    </div> <!-- /#list -->

    <div id="bottom" class="row">
        <div class="col-md-12">
            <ul class="pagination">
                <li class="disabled"><a>&lt; Anterior</a></li>
                <li class="disabled"><a>1</a></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>

                <li class="next"><a href="#" rel="next">Próximo &gt;</a></li>
            </ul><!-- /.pagination -->
        </div>
    </div> <!-- /#bottom -->
</div>



<?php $this->render('common/footer'); ?>
