<?php $this->render('common/header'); ?>
<?php $this->render('common/session'); ?>


<div id="main" class="container-fluid">
    <div id="top" class="row">
        <div class="col-md-3">
            <?php $this->render('common/login'); ?><!--navbar-->
        </div>
        <div class="col-md-6">
            <?php $this->render('common/search'); ?>
        </div>
    </div> 
    <?php $this->render('common/logout'); ?>
     <?php if (session()->has('_errosearch')): ?>
        <div class="alert alert-danger" role="alert"><?= session()->getAndRemove('_errosearch'); ?></div>
    <?php endif; ?>
    <?php if (session()->has('_erro')): ?>
        <div class="alert alert-danger" role="alert"><?= session()->getAndRemove('_erro'); ?></div>
    <?php endif; ?>

    <?php if (session()->has('_sucesso')): ?>
        <div class="alert alert-success" role="alert"><?= session()->getAndRemove('_sucesso'); ?>
        </div>
    <?php endif; ?>

    <hr />
    <?php $this->render('common/navbar'); ?><!--navbar-->

    <div class="row">

        <?php foreach ($imoveis as $dados): ?>
            <div class="col-sm-6 col-md-4">

                <div class="thumbnail">
                    <img src="../imagens/produtos/<?= $dados->id ?>/<?= $dados->imagem ?>" alt="<?= $dados->imagem ?>" width="90%"  style=" height: 300px;">
                    <div class="caption">
                        <h3>Titulo:<strong><?= $dados->titulo ?></strong></h3>
                        <address>
                            <h4><strong>Cordigo: </strong><?= $dados->codigo ?> <strong>Tipo: </strong><?= $dados->tipo ?><br></h4>

                            <strong>Endereço: </strong><?= $dados->rua ?> N°</strong><?= $dados->numero ?><br>
                            <strong>Bairro: </strong><?= $dados->bairro ?><br>
                            <strong>Cidade: </strong><?= $dados->cidade ?>
                            <strong>Estado: </strong><?= $dados->estado ?><br>
                            <strong>Complemento: </strong><?= $dados->complemento ?><br>
                            <strong>Status: </strong><?= $dados->forma ?>
                            <strong>Valor: </strong><?= $dados->preco ?><br>
                            <strong>Area: </strong><?= $dados->area ?> <small>Mt²</small>&nbsp;
                            <strong>Quarto: </strong><?= $dados->quarto ?>&nbsp;
                            <strong>Suite: </strong><?= $dados->suite ?><br>
                            <strong>Banheiro: </strong><?= $dados->banheiro ?>&nbsp;
                            <strong>Sala: </strong><?= $dados->sala ?>&nbsp;
                            <strong>Garagem: </strong><?= $dados->garagem ?><br>
                        </address>

                        <!--<p><a href="<?= url()->route('cadastro.editar', ['id' => $dados->id]); ?>" class="btn btn-primary" role="button">Editar</a> 
                            <a href="<?= url()->route('cadastro.delete', ['id' => $dados->id]); ?>" class="btn btn-danger" role="button">Excluir</a></p>-->
                    </div>
                </div>
            </div><?php endforeach; ?>
    </div>


    <?php $this->render('common/footer'); ?>
