<?php $this->render('common/header'); ?>
<?php $this->render('common/session'); ?>

<div id="main" class="container-fluid">
    <div id="top" class="row">
        <div class="col-md-3">
            <?php $this->render('common/login'); ?><!--navbar-->
        </div>
        <div class="col-md-6">
            <?php $this->render('common/search_lista'); ?>
        </div>
    </div> 
    <?php $this->render('common/logout'); ?>
    <?php if (session()->has('_errosearch')): ?>
        <div class="alert alert-danger" role="alert"><?= session()->getAndRemove('_errosearch'); ?></div>
    <?php endif; ?>
    <?php if (session()->has('_erro')): ?>
        <div class="alert alert-danger" role="alert"><?= session()->getAndRemove('_erro'); ?></div>
    <?php endif; ?>

    <?php if (session()->has('_sucesso')): ?>
        <div class="alert alert-success" role="alert"><?= session()->getAndRemove('_sucesso'); ?>
        </div>
    <?php endif; ?>

    <hr />
    <?php $this->render('common/navbar'); ?><!--navbar-->
        <div class="container-fluid text-center">
            <div class="row">
                <div class="col-md-12">
            <?php foreach ($imoveis as $dados):?>
            <table class="table table-striped table-bordered table-hover">
                <tr>
                    <th width="5%">Cód</th>
                    <th width="13%">Titulo</th>
                    <th width="10%">Tipo</th>
                    <th width="15%">Rua</th>
                    <th width="10%">Cidade</th>
                    <th width="10%">Bairro</th>
                    <th width="5%">Uf</th>
                    <th width="5%">Status</th>
                    <th width="5%">Preço</th>
                    <th width="5%">Imagem</th>
                    <th width="7%">Ação</th>
                </tr>
                <tr>
                    <td><?=$dados->codigo;?></td>
                    <td><?=$dados->titulo;?></td>
                    <td><?=$dados->tipo;?></td>
                    <td><?=$dados->rua;?></td>
                    <td><?=$dados->cidade;?></td>
                    <td><?=$dados->bairro;?></td>
                    <td><?=$dados->estado;?></td>
                    <td><?=$dados->forma;?></td>
                    <td><?=$dados->preco;?></td>
                    
                    <td class="text-center">
                        <img src="../imagens/produtos/<?= $dados->id ?>/<?= $dados->imagem?>" alt="<?=$dados->imagem?>" width="40" height="40">
                    </td>
                    <td>
                        <a title="Visualizar" href="<?= url()->route('busca.search',['search'=>$dados->codigo])?>">
                            <i class="glyphicon glyphicon-eye-open"></i>
                        </a>
                        <a title="Editar" href="<?= url()->route('cadastro.editar',['id'=>$dados->id])?>">
                            <i class="glyphicon glyphicon-edit"></i>
                        </a>
                        <a title="Deletar" href="<?= url()->route('cadastro.delete_lista',['id'=>$dados->id])?>">
                            <i class="glyphicon glyphicon-trash"></i>
                        </a>
                    </td>
                </tr>
                
            </table>
            <?php endforeach;?>
                    </div>
            </div>    
        </div>
    <?php $this->render('common/footer'); ?>
