<?php
$this->render('common/header');


?>

<div id="main" class="container-fluid">

    <div id="top" class="row">
        <div class="col-md-3">
            <?php $this->render('common/login'); ?><!--navbar-->
        </div>
        <div class="col-md-6">
            <div class="input-group h2">
                <input name="data[search]" class="form-control" id="search" type="text" placeholder="Pesquisa de Itens">
                <span class="input-group-btn">
                    <button type="submit" class="btn btn-primary">
                        <span class="glyphicon glyphicon-search"></span>
                    </button>
                </span>
            </div>
        </div>
        
    </div> <!-- /#top -->
    <!--mensagem de erro DELETAR!!!-->
    <?php $this->render('common/logout'); ?><!--logout-->
    <?php if(session()->has('_erro')): ?>
        <div class="alert alert-danger" role="alert"><?=session()->getAndRemove('_erro');?></div>
    <?php endif;  ?>
        
    <?php if (session()->has('_sucesso')): ?>
        <div class="alert alert-success" role="alert">
            <?= session()->getAndRemove('_sucesso'); ?>
        </div>
    <?php endif; ?>
        
    <hr /><?php $this->render('common/navbar'); ?><!--navbar-->
    
    <div class="row">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
        <img src="http://www.austenmorris.com/wp-content/uploads/2017/06/Tech-Sector-V2.jpg" alt="..." width="90%">
      <div class="caption">
          <h3>Titulo</h3>
        <address>
            <strong>Cordigo: </strong>0001 <strong>Tipo: </strong>Apartamento<br><br>
            <div class="text-primary">Endereço</div>
            <strong>Rua: </strong>Tomaz Lupo, <strong>N°</strong>251<br>
            <strong>Bairro: </strong>Vila Gomes<br>
            <strong>Cidade: </strong>São Paulo<br>
            <strong>Estado: </strong>SP<br>
            <strong>Complemento: </strong>Casa Terrea<br>
            <strong>Status: </strong>Venda<br>
            <strong>Valor: </strong>R$ 5000<br>
            <strong>Area: </strong>100 <small>Mt²</small><br>
            <strong>Quarto: </strong>1<br>
            <strong>Suite: </strong>1<br>
            <strong>Banheiro: </strong>1<br>
            <strong>Sala: </strong>1<br>
            <strong>Garagem: </strong>1<br>
        </address>
        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
      </div>
    </div>
  </div>
</div>


<?php $this->render('common/footer'); ?>
