
<div>
    <iframe src="https://www.digitalcontrol.com.br/" width="100%;" height="100%"></iframe></div>

<?php $this->render('common/header'); ?>

<div id="dControlModal" class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <img class="text-left" src="<?= assets()->img('logo_digitalControl.png'); ?>" style=" width: -webkit-fill-available;">
            <div class="modal-body">
                <form role="form" method="post" action="<?= url()->route('login.logar'); ?>">
                    <fieldset>
                        <div class="form-group">
                            <input class="form-control" placeholder="E-mail" name="email" type="text">
                        </div>
                        <div class="form-group">
                            <input class="form-control" placeholder="Password" name="password" type="password" value="">
                        </div>
                        <div class="checkbox">
                            <label>
                                <input name="remember" type="checkbox" value="Remember Me"> Lembra-me
                            </label>
                        </div>
                        <input class="btn btn-lg btn-success btn-block" type="submit" value="Login">
                    </fieldset>
                </form>
            </div>

            <!-- Modal footer 
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
            </div>-->


        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('#dControlModal').modal('show');
    });
</script>