<nav class="navbar navbar-default">
            <div class="container-fluid">
                    <div class="navbar-header">
                            <a class="navbar-brand" href="">GROUP Digital</a>
                    </div>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="<?= url()->route('menu.index');?>">Home</a></li>
                        <li><a href="<?= url()->route('cadastro.index');?>">Cadastrar Imóveis</a></li>
                        <li><a href="<?= url()->route('xml.index');?>">Importar XML</a></li>
                            
                    </ul>
            </div>
        </nav>