<form action="<?= url()->route('busca.search')?>" method="post">
                <div class="input-group h2">
                    <input name="search" class="form-control" id="search" type="text" placeholder="Digite o código">
                    <span class="input-group-btn">
                        <button type="submit" class="btn btn-primary">
                            <span class="glyphicon glyphicon-search"></span>
                        </button>
                    </span>
                </div>
            </form>